### ISSUE TITLE
 Could not resolve "partysocket"

### ISSUE THREAD

**Issue by thomastraum** [partykit/partykit#149]
thank you for making partykit. I wanted to play with the examples, but might be doing something wrong, or possibly related to https://discord.com/channels/1051830863576453180/1117203052655550464 as well.

I installed `sudo apt install libc++1`

I am on wsl2 ubuntu 22, windows 10

```
thomas@tm-blade ~/c/p/e/basic (main)> pwd                                                                                                     (base) 
/home/thomas/code/partykit/examples/basic
npm install partykit@beta y-partykit@beta
npx partykit dev ./src/server.ts     

```

```
Loading config from partykit.json
Warning: serving assets are not yet supported in dev mode

✘ [ERROR] Could not resolve "partysocket"

    src/client.ts:4:24:
      4 │ import PartySocket from "partysocket";
        ╵                         ~~~~~~~~~~~~~

  You can mark the path "partysocket" as external to exclude it from the bundle, which will remove
  this error.

Error: Command failed with exit code 1: esbuild src/client.ts --bundle --outdir=public/dist --format=esm
    at makeError (file:///home/thomas/code/partykit/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/thomas/code/partykit/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runBuild (file:///home/thomas/code/partykit/examples/basic/node_modules/partykit/dist/bin.mjs:1100:9) {
  shortMessage: 'Command failed with exit code 1: esbuild src/client.ts --bundle --outdir=public/dist --format=esm',
  command: 'esbuild src/client.ts --bundle --outdir=public/dist --format=esm',
  escapedCommand: 'esbuild "src/client.ts" --bundle "--outdir=public/dist" "--format=esm"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

other examples I am getting: 

```
thomas@tm-blade ~/c/p/e/basic (main) [1]> cd ../yjs                                                                                                              (base) 
thomas@tm-blade ~/c/p/e/yjs (main)> npx partykit dev ./src/server.ts                                                                                             (base) 
Build succeeded, starting server...
[pk:inf] Ready on http://127.0.0.1:1999/
[pk:inf] GET / 404 Not Found (2ms)


```
I had problems with 127.0.0.1 in the past with wsl2 and I think localhost works better. In this case I am getting `not found` via `localhost` too

**Comment by threepointone** [comment]
wait, I think I just spotted that you haven't installed it. try npm install `partysocket@beta` and let me know if that works?

**Comment by thomastraum** [comment]
thanks! not sure how i missed this.

Now I am getting this, I am running this from the partykit repo, cd'ing into examples/basic 

```

thomas@tm-blade ~/c/p/e/basic (main)> npm install partykit@beta y-partykit@beta partysocket@beta                                                                               (base) 

changed 5 packages, and audited 264 packages in 5s

64 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
thomas@tm-blade ~/c/p/e/basic (main)> npx partykit dev src/server.ts                                                                                                           (base) 
Loading config from partykit.json
Warning: serving assets are not yet supported in dev mode


  public/dist/client.js  15.2kb

Build succeeded, starting server...
*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Address already in use; toString() = 127.0.0.1:9229
stack: /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e8cf6a /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e8cd0f /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e8af75 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1547ce5 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1547f30 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@150bfdd /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1510d47 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1510ac4 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1510aac /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ec38d8 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ec34c9 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ec1788 /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ec154a /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1501293 /lib/x86_64-linux-gnu/libc.so.6@29d8f /lib/x86_64-linux-gnu/libc.so.6@29e3f /home/thomas/code/partykit/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1501024
Error reloading local server: MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/home/thomas/code/partykit/node_modules/miniflare/dist/src/index.js:9144:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #init (/home/thomas/code/partykit/node_modules/miniflare/dist/src/index.js:8898:5)
    at async Mutex.runWith (/home/thomas/code/partykit/node_modules/miniflare/dist/src/index.js:2789:16)
    at async #waitForReady (/home/thomas/code/partykit/node_modules/miniflare/dist/src/index.js:9159:5)
    at async MiniflareServer.onBundleUpdate (file:///home/thomas/code/partykit/examples/basic/node_modules/partykit/dist/bin.mjs:940:19) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
Failed to start inspector: Error: Timed out waiting for port 9230
    at Timeout.<anonymous> (file:///home/thomas/code/partykit/examples/basic/node_modules/partykit/dist/bin.mjs:361:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)



```

**Comment by threepointone** [comment]
oh hmm, do you have any other dev servers running in other terminal windows?

(a fix for us to do is to use alternate ports if they're already in use)

**Comment by thomastraum** [comment]
I figured it out.. all my fault. :-)
It was a port issue but then I stumbled at a few other hurdles. 

Maybe would help if in the package.json of the examples it has all the packages listed, so a `npm install` inside the specific example would install it all. `partysocket` is not mentioned on the readme I think. 

great library cant wait to now play with it some more.
