### ISSUE TITLE
starting another `partykit dev` instance throws

### ISSUE THREAD

**Issue by astahmer** [partykit/partykit#257]
which makes sense ! but maybe it would be better to find another available port instead ? or clarify what the issue is in the logged error.

this error happens on the 2nd instance, the first doesn't complain:

```
> @partykit/examples-basic@0.0.0 start /Users/astahmer/dev/alex/partyrpc/examples/basic
> partykit dev --var A=456 B=789=123 --define SOME_GLOBAL=88888

🎈 PartyKit v0.0.0-1f86d17
---------------------------
▲ [WARNING] Serving static assets in dev mode is experimental and may change any time


Build succeeded, starting server...
Error reloading local server: MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/astahmer/dev/alex/partyrpc/node_modules/.pnpm/miniflare@3.20230814.1/node_modules/miniflare/dist/src/index.js:9383:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #init (/Users/astahmer/dev/alex/partyrpc/node_modules/.pnpm/miniflare@3.20230814.1/node_modules/miniflare/dist/src/index.js:9140:5)
    at async Mutex.runWith (/Users/astahmer/dev/alex/partyrpc/node_modules/.pnpm/miniflare@3.20230814.1/node_modules/miniflare/dist/src/index.js:2797:16)
    at async #waitForReady (/Users/astahmer/dev/alex/partyrpc/node_modules/.pnpm/miniflare@3.20230814.1/node_modules/miniflare/dist/src/index.js:9400:5)
    at async MiniflareServer.onBundleUpdate (file:///Users/astahmer/dev/alex/partyrpc/node_modules/.pnpm/partykit@0.0.0-1f86d17_@types+react@18.2.20/node_modules/partykit/dist/bin.mjs:1382:19) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
Failed to start inspector: Error: Timed out waiting for port 9230
    at Timeout.<anonymous> (file:///Users/astahmer/dev/alex/partyrpc/node_modules/.pnpm/partykit@0.0.0-1f86d17_@types+react@18.2.20/node_modules/partykit/dist/bin.mjs:792:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

^C%  
```

**Comment by threepointone** [comment]
Yup, known issue, thanks for filing this, we should definitely fix it! We can just find another free port.

**Comment by threepointone** [comment]
fixed by https://github.com/partykit/partykit/pull/281
