### ISSUE TITLE
Error after running npx partykit : Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by lpalombo** [partykit/partykit#294]
I'm not having any luck running any of the latest partykit cli commands on my dev environment. I've narrowed it down to the [PR that merged in Clerk authentication](https://github.com/partykit/partykit/commit/c80e6b227341e849b469d62f34f70534ced29d96). The npm package just before that, `partykit@0.0.0-7aab91f`, appears to launch fine but of course deployment does not appear to function correctly.

In the searching I've done on the internet, it appears this error is often related to a [misconfigured webpack configuration](https://stackoverflow.com/a/64715069) so perhaps this issue is upstream on Clerk's side. I've also seen this issue attributed to running node in a WSL2 environment, which I happen to be using...

## Error
```bash
..........ble__environment(){return Li(this,ni,"f")}assertComponentsReady(t){if(!Ji.mountComponentRenderer)throw new Error("ClerkJS was loaded without UI components.");if(!t)throw new Error("ClerkJS components are not ready yet.")}}Ze=new WeakMap,Xe=new WeakMap,ti=new WeakMap,ei=new WeakMap,ii=new WeakMap,ri=new WeakMap,ni=new WeakMap,oi=new WeakMap,si=new WeakMap,ai=new WeakMap,ci=new WeakMap,li=new WeakMap,ui=new WeakMap,hi=new WeakMap,di=new WeakMap,pi=new WeakMap,fi=new WeakMap,mi=new WeakMap,gi=new WeakMap,yi=new WeakMap,vi=new WeakMap,bi=new WeakMap,wi=new WeakMap,_i=new WeakMap,Si=new WeakMap,ki=new WeakMap,Ai=new WeakMap,Ui=new WeakMap,Pi=new WeakMap,Oi=new WeakMap,xi=new WeakMap,Ii=new WeakMap,Ei=new WeakMap,Ci=new WeakMap,Ti=new WeakMap,Mi=new WeakMap,Ri=new WeakMap,ji=new WeakMap,Ni=new WeakMap,Fi=new WeakMap,zi=new WeakMap,Wi=new WeakMap,Ji.version="4.56.0";var Bi=Ji}(),o}()}));

# above is a sample from whatever is logged before the trace below. It's a bunch of minified js code. I assume this is from clerk's minified sourcecode?

Error: Automatic publicPath is not supported in this browser
    at /home/xxx/xxx/xxx/node_modules/.pnpm/@clerk+clerk-js@4.56.0_@babel+core@7.22.11_@types+react@18.0.27_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/clerk-js/dist/clerk.headless.js:2:47936
    at /home/xxx/xxx/xxx/node_modules/.pnpm/@clerk+clerk-js@4.56.0_@babel+core@7.22.11_@types+react@18.0.27_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/clerk-js/dist/clerk.headless.js:2:48077
    at /home/xxx/xxx/xxx/node_modules/.pnpm/@clerk+clerk-js@4.56.0_@babel+core@7.22.11_@types+react@18.0.27_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/clerk-js/dist/clerk.headless.js:2:148966
    at /home/xxx/xxx/xxx/node_modules/.pnpm/@clerk+clerk-js@4.56.0_@babel+core@7.22.11_@types+react@18.0.27_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/clerk-js/dist/clerk.headless.js:2:84
    at Object.<anonymous> (/home/xxx/xxx/xxx/node_modules/.pnpm/@clerk+clerk-js@4.56.0_@babel+core@7.22.11_@types+react@18.0.27_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/clerk-js/dist/clerk.headless.js:2:223)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
```

## Specs
```
Ubuntu 22.04.2 LTS via WSL2
Node v18.17.1 and v20.5.1
pnpm and npm
```

## Commands Used
```
npx partykit

pnpm install partykit
pnpm partykit #via a script in package.json that simply calls "partykit"

# delete node_modules
npm install
npm partykit
```

**Comment by threepointone** [comment]
Weird, having a look

**Comment by threepointone** [comment]
Looks like they shipped a version a few hours ago that broke it running inside node. fix incoming.

**Comment by threepointone** [comment]
Ok fixed, please update to the latest `@beta` and try again? (`0.0.0-bae7334`)

**Comment by threepointone** [comment]
(Thank you for filing the issue which specific details! It was very helpful to move fast on this)

**Comment by lpalombo** [comment]
works now! no problem and thank you! Feel free to close the issue
