### ISSUE TITLE
Better error-handling for create/init commands  (node < v18)

### ISSUE THREAD

**Issue by patcon** [partykit/partykit#408]
Love this project! Small [maybe] bug report.

In node 16.16.0, `npx partykit@latest init` and `npm create partykit@latest` seem to generally work, but they throw an error.

This makes sense in light of [fetch being added as experimental in v18](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch).

## `npx partykit@latest init`

<details>
<summary>Text of error...</summary>

```
Could not fetch latest versions of partykit and partysocket, defaulting to *
```
</details>

<img width="694" alt="Screen Shot 2023-09-23 at 11 29 52 AM" src="https://github.com/partykit/partykit/assets/305339/2167552d-0950-4e9d-a89f-b7ff9bce27d8">

https://github.com/partykit/partykit/blob/e525f2480e01aa37e5902ba3f8d8299d08f0add8/packages/partykit/src/cli.tsx#L145

## `npm create partykit@latest`

<details>
<summary>Text of error...</summary>

```
Could not fetch latest versions of partykit and partysocket, defaulting to *
ReferenceError: fetch is not defined
    at null.init (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/create-partykit/src/index.tsx:166:7)
    at _Command.<anonymous> (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/create-partykit/src/index.tsx:529:11)
    at _Command.listener (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/commander/lib/command.js:482:17)
    at null.<anonymous> (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/commander/lib/command.js:1300:65)
    at _Command._chainOrCall (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/commander/lib/command.js:1197:12)
    at _Command._parseCommand (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/commander/lib/command.js:1300:27)
    at _Command.parse (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/commander/lib/command.js:909:10)
    at null.<anonymous> (/Users/patcon/.npm/_npx/cadd21533ff9f374/node_modules/create-partykit/src/index.tsx:540:9)
Where should we create your project?
```
</details>

<img width="870" alt="Screen Shot 2023-09-23 at 11 54 35 AM" src="https://github.com/partykit/partykit/assets/305339/5f49eb9c-d40e-493a-a4fe-01a460cf29d6">

## Proposed Solution

Better error-handling when fetch isn't available, or more explicitly saying that anything below some node version is unsupported and may display errors.

**Comment by threepointone** [comment]
fixed node 16 support in https://github.com/partykit/partykit/pull/410
(but we'll probably deprecate node 16 support soon, with good error messages)
