### ISSUE TITLE
"ReferenceError: Headers is not defined" during partykit deploy

### ISSUE THREAD

**Issue by MaxBittker** [partykit/partykit#451]
running `npx partykit deploy` for the first time :) 
it pops a browser authorization which seems to succeed, but then I get this error in my terminal: 
```
node -v
v16.20.2
```

```
🎈 PartyKit v0.0.23
--------------------
Attempting to login...
ReferenceError: Headers is not defined
    at Object.request (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34855:148)
    at Function._fetch (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33198:42)
    at Yt._baseGet (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33233:35)
    at Yt.fetch (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33481:54)
    at Bi.<anonymous> (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34730:70)
    at Bi.load (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34423:205)
    at file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:91843:17
    at fetchClerkClientToken (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:91855:23)
    at createClerkSession (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:93840:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: Headers is not defined
    at Object.request (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34855:148)
    at Function._fetch (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33198:42)
    at $t._baseGet (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33233:35)
    at $t.fetch (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33358:27)
    at Bi.<anonymous> (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34730:112)
    at Bi.load (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34423:205)
    at file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:91843:17
    at fetchClerkClientToken (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:91855:23)
    at createClerkSession (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:93840:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: Headers is not defined
    at Object.request (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:34855:148)
    at Function._fetch (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33198:42)
    at We._baseMutate (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33237:35)
    at We._basePost (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33241:27)
    at We.create (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:33889:371)
    at fetchClerkClientToken (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:91856:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createClerkSession (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:93840:16)
    at async getUser (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:93772:18)
    at async deploy (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:96981:16)
file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:103744
    throw err;
    ^

Error: Flow did not complete: {"pathRoot":"/client/sign_ins","status":null,"supportedIdentifiers":[],"supportedFirstFactors":[],"supportedSecondFactors":[],"firstFactorVerification":{"pathRoot":"","status":null,"strategy":null,"nonce":null,"externalVerificationRedirectURL":null,"attempts":null,"expireAt":null,"error":null,"verifiedAtClient":null},"secondFactorVerification":{"pathRoot":"","status":null,"strategy":null,"nonce":null,"externalVerificationRedirectURL":null,"attempts":null,"expireAt":null,"error":null,"verifiedAtClient":null},"identifier":null,"createdSessionId":null,"userData":{}}
    at fetchClerkClientToken (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:91861:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createClerkSession (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:93840:16)
    at async getUser (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:93772:18)
    at async deploy (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:96981:16)
    at async _Command.<anonymous> (file:///Users/max/workplace/farmy/node_modules/partykit/dist/bin.mjs:103806:3)
    
    ```

**Comment by threepointone** [comment]
Hmm, we don't use Headers directly, but a dependency might be doing so. I think you may be using node 16, can you try with node 18 and see if the problem persists?

**Comment by MaxBittker** [comment]
that fixed it

**Comment by MaxBittker** [comment]
thank you
