### ISSUE TITLE
Bug: `partysocket` error isn't working properly (`reason` and `code` are undefined)

### ISSUE THREAD

**Issue by titanism** [partykit/partykit#537]
In the original fork of `partysocket`, an error was created with a reason and code.

However in the updated `partysocket` project, this no longer functions properly:

```sh
Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/Users/user/Projects/web/node_modules/.pnpm/websocket-as-promised@2.0.1/node_modules/websocket-as-promised/src/index.js:409:19)
    at _ReconnectingWebSocket.listener (/Users/user/Projects/web/node_modules/.pnpm/websocket-as-promised@2.0.1/node_modules/websocket-as-promised/src/index.js:340:64)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at _ReconnectingWebSocket.dispatchEvent (node:internal/event_target:679:26)
    at _ReconnectingWebSocket._handleClose (/Users/user/Projects/web/node_modules/.pnpm/partysocket@0.0.12/node_modules/partysocket/dist/index.js:444:10)
    at _ReconnectingWebSocket._disconnect (/Users/user/Projects/web/node_modules/.pnpm/partysocket@0.0.12/node_modules/partysocket/dist/index.js:393:12)
    at WebSocket._handleError (/Users/user/Projects/web/node_modules/.pnpm/partysocket@0.0.12/node_modules/partysocket/dist/index.js:424:10)
    at callListener (/Users/user/Projects/web/node_modules/.pnpm/ws@8.14.2_nn4cfacdngcg7bs47xs3zpla7u/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onError (/Users/user/Projects/web/node_modules/.pnpm/ws@8.14.2_nn4cfacdngcg7bs47xs3zpla7u/node_modules/ws/lib/event-target.js:230:9)
    at WebSocket.emit (node:events:513:28)
    at emitErrorAndClose (/Users/user/Projects/web/node_modules/.pnpm/ws@8.14.2_nn4cfacdngcg7bs47xs3zpla7u/node_modules/ws/lib/websocket.js:1016:13)
    at ClientRequest.<anonymous> (/Users/user/Projects/web/node_modules/.pnpm/ws@8.14.2_nn4cfacdngcg7bs47xs3zpla7u/node_modules/ws/lib/websocket.js:864:5)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
```

**Comment by threepointone** [comment]
Thanks for reporting this! We'll fix this, happy to take a PR as well.

**Comment by threepointone** [comment]
This should now be fixed, closing. Feel free to use https://github.com/threepointone/test-websocket-as-promised-partysocket as a test repo to make any future reproductions. 

re: the error, those are close events? If you can make a repro with an expected error event and lemme know what the expected behaviour is, I'd be happy to have a look.
