### ISSUE TITLE
Sanitise Party `name` on partykit init

### ISSUE THREAD

**Issue by bdsqqq** [partykit/partykit#727]
Partykit has been a joy to work with, as someone who tried implementing a fraction of the functionality, I appreciate so much all the care and effort that went into making such an amazing piece of software. Kudos to the team!

BUT recently I hit an error that embarrassingly costed a fair amount of time to deal with: **when initing partykit in a project with special characters in the name(especially common for monorepos), the init script will not strip them out when generating the config file, causing a validation error on both `dev` and `deploy`**

The error you're met with is not the worst, but it is weird to see it being thrown by the node module with no indication that it was caused by my config other than the `name` in the `path` object Zod logs; see attached 1 for an example of the error.

This is a feature request, and to be fair I might give it a shot later this weekend, BUT, can partykit convert the special characters into something valid when initing?

---

1. Example of error caused when trying to run `dev` or `deploy` in a project with special characters in the config generated by `init`
```
🎈 PartyKit v0.0.73
--------------------
Loading environment variables from ../../../../.env
Invalid party name: @haxiom/nextjs-party
file:///Users/bdsqqq/Library/pnpm/store/v3/tmp/dlx-70245/node_modules/.pnpm/partykit@0.0.73/node_modules/partykit/dist/bin.mjs:87795
    throw err;
    ^

ZodError: [
  {
    "code": "custom",
    "message": "must satisfy /^[a-z0-9_-]+$/",
    "path": [
      "name"
    ]
  }
]
    at get error [as error] (file:///Users/bdsqqq/Library/pnpm/store/v3/tmp/dlx-70245/node_modules/.pnpm/partykit@0.0.73/node_modules/partykit/dist/bin.mjs:71195:23)
    at _ZodObject.parse (file:///Users/bdsqqq/Library/pnpm/store/v3/tmp/dlx-70245/node_modules/.pnpm/partykit@0.0.73/node_modules/partykit/dist/bin.mjs:71294:18)
    at getConfig (file:///Users/bdsqqq/Library/pnpm/store/v3/tmp/dlx-70245/node_modules/.pnpm/partykit@0.0.73/node_modules/partykit/dist/bin.mjs:76348:16)
    at deploy (file:///Users/bdsqqq/Library/pnpm/store/v3/tmp/dlx-70245/node_modules/.pnpm/partykit@0.0.73/node_modules/partykit/dist/bin.mjs:79815:18)
    at _Command.<anonymous> (file:///Users/bdsqqq/Library/pnpm/store/v3/tmp/dlx-70245/node_modules/.pnpm/partykit@0.0.73/node_modules/partykit/dist/bin.mjs:87867:9) {
  issues: [
    {
      code: 'custom',
      message: 'must satisfy /^[a-z0-9_-]+$/',
      path: [ 'name' ]
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'custom',
      message: 'must satisfy /^[a-z0-9_-]+$/',
      path: [ 'name' ]
    }
  ]
}
```

**Comment by threepointone** [comment]
Fixed by https://github.com/partykit/partykit/pull/728, available in partykit@0.0.74. Thanks for reporting!
