### ISSUE TITLE
Error: invalid or missing json property for binding PARTYKIT_AI

### ISSUE THREAD

**Issue by kculmback-eig** [partykit/partykit#883]
Started getting this error when trying to deploy our partykit instance. We've been using/deploying partykit successfully for a while but today started getting the error below when deploying. We haven't changed anything for a few weeks, so I'm not sure why we would suddenly start getting this error. We aren't using any of Partykit's AI features.

On the server side we're using `y-partykit` for our main server and then a very basic event bus server that implements `Party.Server`. 

Has there been a recent update that would cause this error to happen?

```
file:///actions-runner/_work/{repo}/node_modules/.pnpm/partykit@0.0.105/node_modules/partykit/dist/bin.mjs:91459
    throw err;
    ^

Error: invalid or missing json property for binding PARTYKIT_AI
    at fetchResult (file:///actions-runner/_work/{repo}/node_modules/.pnpm/partykit@0.0.105/node_modules/partykit/dist/bin.mjs:84870:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploy (file:///actions-runner/_work/{repo}/node_modules/.pnpm/partykit@0.0.105/node_modules/partykit/dist/bin.mjs:90908:21)
    at async _Command.<anonymous> (file:///actions-runner/_work/{repo}/node_modules/.pnpm/partykit@0.0.105/node_modules/partykit/dist/bin.mjs:91548:3)
```

**Comment by kculmback-eig** [comment]
I get the same issue when following the quickstart guide to deploy a new partykit instance.

```
npm create partykit@latest --typescript --git
cd ./new-project
npx partykit deploy

Error: invalid or missing json property for binding PARTYKIT_AI
    at fetchResult (file:///new-project/node_modules/partykit/dist/bin.mjs:84791:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploy (file:///new-project/node_modules/partykit/dist/bin.mjs:90818:21)
    at async _Command.<anonymous> (file:///new-project/node_modules/partykit/dist/bin.mjs:91458:3)
```

**Comment by danny-hunt** [comment]
Also encountering this issue

`partykit deploy --preview ${BRANCH_NAME_CLEAN} --var NEXT_APP_URL=https://${VERCEL_URL} --var DATABASE_URL=${DATABASE_URL}`

```
🎈 PartyKit v0.0.103
---------------------
Deploying...
file:///vercel/path0/node_modules/partykit/dist/bin.mjs:91444
    throw err;
    ^

Error: invalid or missing json property for binding PARTYKIT_AI
    at fetchResult (file:///vercel/path0/node_modules/partykit/dist/bin.mjs:84866:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploy (file:///vercel/path0/node_modules/partykit/dist/bin.mjs:90893:21)
    at async _Command.<anonymous> (file:///vercel/path0/node_modules/partykit/dist/bin.mjs:91533:3)

Node.js v18.19.1
error: script "build" exited with code 7
Error: Command "bun run build" exited with 7
```

**Comment by threepointone** [comment]
Sorry about this, I think there's been a breaking change in CF. I'll try to fix it this weekend

**Comment by threepointone** [comment]
This should be fixed now!  You don't have to update anything, just try to deploy again. I'm closing this issue, but please comment if it hasn't been fixed for you

**Comment by kculmback-eig** [comment]
@threepointone we were able to successfully deploy this morning; thank you!
