### ISSUE TITLE
Error: workers.api.error.unknown

### ISSUE THREAD

**Issue by RamDurgaSai** [partykit/partykit#904]
Getting below error while deploying partykit

 npx partykit deploy
🎈 PartyKit v0.0.100
Preparing 2 assets for upload...
Uploading 2 assets...
Uploaded dist/client.js.map
Uploaded dist/client.js
Updating asset index...
Deploying...
file:///Users/user/Documents/GitHub/project-hub/packages/partykit/node_modules/partykit/dist/bin.mjs:91369
    throw err;
    ^

Error: workers.api.error.unknown
    at fetchResult (file:///Users/user/Documents/GitHub/project-hub/packages/partykit/node_modules/partykit/dist/bin.mjs:84791:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploy (file:///Users/user/Documents/GitHub/project-hub/packages/partykit/node_modules/partykit/dist/bin.mjs:90818:21)
    at async _Command.<anonymous> (file:///Users/user/Documents/GitHub/project-hub/packages/partykit/node_modules/partykit/dist/bin.mjs:91458:3)

Node.js v20.15.1

**Comment by threepointone** [comment]
Are you still getting this error?

**Comment by RamDurgaSai** [comment]
Yes, still getting same error. 

Here's the latest logs 

```
🎈 PartyKit v0.0.100
---------------------
Deploying...
file:///home/ubuntu/party/node_modules/partykit/dist/bin.mjs:91369
    throw err;
    ^

Error: workers.api.error.unknown
    at fetchResult (file:///home/ubuntu/party/node_modules/partykit/dist/bin.mjs:84791:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploy (file:///home/ubuntu/party/node_modules/partykit/dist/bin.mjs:90818:21)
    at async _Command.<anonymous> (file:///home/ubuntu/party/node_modules/partykit/dist/bin.mjs:91458:3)

Node.js v20.17.0

**Comment by MaxBittker** [comment]
I'm getting this error as well, on PartyKit v0.0.110, and only when i have 
`  "placement": { "mode": "smart" },` 
set

**Comment by RamDurgaSai** [comment]
I don't have any placement key, but still getting same error, 

Here's the files 

### package.json
```json
{
  "name": "partykit",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "partykit dev --live",
    "deploy": "partykit deploy"
  },
  "dependencies": {
    "partysocket": "^1.0.1"
  },
  "devDependencies": {
    "partykit": "^0.0.100",
    "typescript": "^5.4.2"
  }
}
```

### partykit.json

```json
{
  "$schema": "https://www.partykit.io/schema.json",
  "name": "hub-party",
  "main": "src/server.ts",
  "compatibilityDate": "2024-07-08",
  "serve": {
    "path": "public",
    "build": "src/client.ts"
  }
}
```

### src/server.ts

```ts
import type * as Party from "partykit/server";

interface User {
  userId: string;
  avatar: string;
  name: string;
  cursor?: { x: number; y: number };
}

interface ConnectionState {
  rooms: Set<string>;
}

export default class Server implements Party.Server {
  private onlineUsers = new Map<string, Map<string, User>>();

  constructor(readonly room: Party.Room) {}
  async onStart() {
    console.log("Server started");
  }
  async onConnect(connection: Party.Connection, ctx: Party.ConnectionContext) {
    console.log(`Client connected: ${connection.id}`);
    connection.setState({ rooms: new Set<string>() } as ConnectionState);
  }
  async onClose(connection: Party.Connection) {
    console.log(`Client disconnected: ${connection.id}`);
    this.removeUserFromAllRooms(connection);
  }
  async onMessage(message: string | ArrayBuffer, connection: Party.Connection) {
    if (typeof message !== "string") return;
    const parsedMessage = JSON.parse(message);
    switch (parsedMessage.event) {
      case "joinRoom":
        this.handleJoinRoom(parsedMessage.data, connection);
        break;
      case "leaveRoom":
        this.handleLeaveRoom(parsedMessage.data, connection);
        break;
      case "cursorPosition": // Handle cursor position updates
        this.handleCursorPosition(parsedMessage.data, connection);
        break;
      default:
        console.log("Unknown event");
    }
  }
  private handleJoinRoom(
    data: { room: string; userId: string; avatar: string; name: string },
    connection: Party.Connection
  ) {
    const { room, userId, avatar, name } = data;
    // Add the user to the room
    if (!this.onlineUsers.has(room)) {
      this.onlineUsers.set(room, new Map());
    }
    this.onlineUsers.get(room)!.set(connection.id, { userId, avatar, name });
    // Add the room to the connection state
    const connectionState = connection.state as ConnectionState;
    connectionState.rooms.add(room);
    connection.setState(connectionState);
    // Broadcast the updated online users to the room
    this.broadcastToRoom(room, {
      event: "onlineUsers",
      data: Array.from(this.onlineUsers.get(room)!.values()),
    });
  }
  private handleLeaveRoom(
    data: { room: string; userId: string },
    connection: Party.Connection
  ) {
    const { room } = data;
    // Remove the user from the room
    if (this.onlineUsers.has(room)) {
      this.onlineUsers.get(room)!.delete(connection.id);
      // Broadcast the updated online users to the room
      this.broadcastToRoom(room, {
        event: "onlineUsers",
        data: Array.from(this.onlineUsers.get(room)!.values()),
      });
    }
    // Remove the room from the connection state
    const connectionState = connection.state as ConnectionState;
    connectionState.rooms.delete(room);
    connection.setState(connectionState);
  }
  private removeUserFromAllRooms(connection: Party.Connection) {
    const connectionState = connection.state as ConnectionState;
    connectionState.rooms.forEach((room) => {
      if (this.onlineUsers.has(room)) {
        this.onlineUsers.get(room)!.delete(connection.id);
        this.broadcastToRoom(room, {
          event: "onlineUsers",
          data: Array.from(this.onlineUsers.get(room)!.values()),
        });
      }
    });
    connectionState.rooms.clear();
    connection.setState(connectionState);
  }
  private broadcastToRoom(room: string, message: any) {
    for (const conn of this.room.getConnections()) {
      conn.send(JSON.stringify(message));
    }
  }
  private handleCursorPosition(
    data: { room: string; userId: string; cursor: { x: number; y: number } },
    connection: Party.Connection
  ) {
    const { room, userId, cursor } = data;
    if (!this.onlineUsers.has(room)) return;
    const user = this.onlineUsers.get(room)!.get(connection.id);
    if (user) {
      user.cursor = cursor;
      this.broadcastToRoom(room, {
        event: "cursorPosition",
        data: { userId, cursor },
      });
    }
  }
}
```

**Comment by threepointone** [comment]
Thanks for the repro and the reports folks, annoyingly I'm not able to reproduce this here, which is confusing me. I can follow up with the cloudflare team early next week.

**Comment by threepointone** [comment]
actually hmm I'm able to reproduce it now for smart placement, digging in some more

**Comment by threepointone** [comment]
Ok I figured out an edge case for the smart placement error and fixed it, @MaxBittker you should be unblocked now, no noeed to update, just try deploying again with the placement config. 

@RamDurgaSai I'm still struggling to reproduce your error. Could you try updating your partykit version and trying? If possible can you make a standalone repro that has the error and that I can check out here locally?
