### ISSUE TITLE
Error reloading local server with MiniflareCoreError when running npx partykit dev

### ISSUE THREAD

**Issue by Akshdhiwar** [partykit/partykit#919]
When running the command npx partykit dev, I encounter an error related to the Workers runtime failing to start. The build itself succeeds, but the local server fails to reload with the following error message:

```
Build succeeded, starting server...
Error reloading local server: MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (E:\Blocknotes\simpledocs\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (E:\Blocknotes\simpledocs\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (E:\Blocknotes\simpledocs\node_modules\miniflare\dist\src\index.js:9235:5)
    at async MiniflareServer.onBundleUpdate (file:///E:/Blocknotes/simpledocs/node_modules/partykit/dist/bin.mjs:92748:20) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
```

**Steps to Reproduce**:
Run `npx partykit dev` in the project directory.
Observe the build succeeding.
Notice the error when reloading the local server.

**Expected Behavior:**
The local server should start without any runtime failures after the build succeeds.

**Actual Behavior:**
The server fails to reload, showing an ERR_RUNTIME_FAILURE related to the Workers runtime.

**Environment:** DEV
**OS:** Windows
**Node version:** 20.11.1
**Partykit version:** v0.0.111

**Comment by Akshdhiwar** [comment]
Hey I solved the above error . For reference look here [https://github.com/cloudflare/workers-sdk/issues/4709#issuecomment-2316796076](https://github.com/cloudflare/workers-sdk/issues/4709#issuecomment-2316796076)
